name: Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_DATABASE: testing_db
          MYSQL_ROOT_PASSWORD: password
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing_db
      DB_USERNAME: root
      DB_PASSWORD: password
    steps:
    - name: PHP実行環境を展開する
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: 8
    - name: チェックアウトアクションを実行する
      uses: actions/checkout@v2
    - name: .envをコピーする
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: PHPライブラリをインストールする
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: LaravelのApp keyを作成する
      run: php artisan key:generate
    - name: ディレクトリの権限を変更する
      run: chmod -R 777 storage bootstrap/cache
    - name: DBをマイグレートする
      run: php artisan migrate
    - name: テストを実行する
      run: vendor/bin/phpunit
    - name: hoge
      run: echo hogehoge
